class Config:
    MIN_VELOCITY = 1.5
    JAM_THRESHOLD = 3
    JAM_FRAMES_DURATION = 30
    TARGET_WIDTH = 640
    TARGET_HEIGHT = 360
    GROUND_TRUTH_JAM_SPEED_THRESHOLD = 1.8
    GROUND_TRUTH_JAM_DURATION_FRAMES = 30
    VELOCITY_SMOOTHING_FRAMES = 3
    MIN_VEHICLES_FOR_JAM = 2
    CONFIDENCE_THRESHOLD = 0.4
    STATIONARY_RATIO_THRESHOLD = 0.5
    VELOCITY_VARIANCE_FACTOR = 0.7
